AWS_ACCESS_KEY_ID: "AKIAIADYDQETQOOZ5FTQ"
AWS_SECRET_ACCESS_KEY: "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"
development:
  SENDGRID_USERNAME: "app22666725@heroku.com"
  SENDGRID_PASSWORD: "qpsvvuhu"
  AWS_BUCKET: oscar-bloccit-development
  FACEBOOK_ID: 1438095266448019
  FACEBOOK_SECRET: 9e048127dd240499f623d273a66b3e56
production:
  AWS_BUCKET: oscar-bloccit-production
  FACEBOOK_ID: 1438095266448019
  FACEBOOK_SECRET: 9e048127dd240499f623d273a66b3e56