AWS_ACCESS_KEY_ID: "AKIAIADYDQETQOOZ5FTQ"
AWS_SECRET_ACCESS_KEY: "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"
development:
  SENDGRID_USERNAME: "app22666725@heroku.com"
  SENDGRID_PASSWORD: "qpsvvuhu"
  AWS_BUCKET: oscar-bloccit-development
  FACEBOOK_ID: 569377006512377
  FACEBOOK_SECRET: a1ae5255cf7f5983e89af972907fe91e
production:
  AWS_BUCKET: oscar-bloccit-production
  FACEBOOK_ID: 569377006512377
  FACEBOOK_SECRET: a1ae5255cf7f5983e89af972907fe91e